from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.11.3")


##### setup report #####
configfile: "config/config.yaml"


# report: "report/workflow.rst"


##### rules #####


include: "rules/common.smk"
include: "rules/datasets_download_genome.smk"
include: "rules/salmon_decoys.smk"
include: "rules/salmon_index.smk"
include: "rules/gffread.smk"
include: "rules/star_index.smk"
include: "rules/fastqc.smk"
include: "rules/star.smk"


# include: "rules/qualimap.smk"
# include: "rules/salmon_quant.smk"
# include: "rules/multiqc.smk"

##### target rules #####


rule all:
    input:
        get_final_output(),
    message:
        "RNA-seq pipeline run complete!"
    shell:
        """
        mkdir results/last_run_config_snapshot -p
        cp config/* results/last_run_config_snapshot/
        """
