# workflow/Snakefile

from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.27.1")


##### setup report #####
configfile: "config/config.yaml"


##### rules #####


include: "rules/common.smk"
include: "rules/datasets_download_genome.smk"
include: "rules/sra_tools.smk"
include: "rules/salmon_decoys.smk"
include: "rules/salmon_index.smk"
include: "rules/salmon_quant.smk"
include: "rules/star_index.smk"
include: "rules/star.smk"
include: "rules/fastqc.smk"
include: "rules/qualimap.smk"
include: "rules/multiqc.smk"


##### target rules #####


rule snapshot_config:
    input:
        directory("config"),
    output:
        "results/last_run_config_snapshot/snapshot_done.txt",
    run:
        cp_config_to_res_dir()
        # Write a marker file to signal completion of the snapshot
        with open(output[0], "w") as f:
            f.write("Configuration snapshot completed.")


rule all:
    input:
        get_final_output(),
        "results/last_run_config_snapshot/snapshot_done.txt",
    message:
        """
        Workflow completed successfully! All final reports and intermediate
        files have been generated.
        """
