# .test/singularity/sra_reads/config/config.yaml

# Path to your SAMPLE SHEET which keeps track of your biological replicates
samples: ".test/sra_reads/config/samples.tsv"

# Path to your sequencing UNIT SHEET which keeps track of your technical
# replicates (e.g. sequencer lanes or resequencing of the same biological
# sample)
units: ".test/sra_reads/config/units.tsv"
