# tucca-rna-seq/workflow/rules/renv.smk
#
# Purpose:
# This Snakefile contains rules to integrate the R package manager `renv` with
# the Conda-based environment of the main Snakemake pipeline. This hybrid
# approach uses Conda to ensure pipeline reproducibility while using renv to
# create a portable, user-friendly interactive R environment for downstream
# analysis.
#
# How it works:
# 1. `renv_snapshot`: This rule runs within the pipeline's R Conda
#    environment. It executes a script that scans the R code used in the
#    pipeline for dependencies and creates a `renv.lock` file. This lockfile
#    is a complete, versioned record of all R packages required by the
#    workflow.
#
# 2. `renv_restore`: This rule uses the `renv.lock` file generated by the
#    `renv_snapshot` rule. It executes `renv::restore()`, which installs all
#    the specified packages into a project-local library at `renv/library/`.
#
# By including these rules in the main `Snakefile`'s `all` rule, this process
# is fully automated. After a successful pipeline run, a user can immediately
# open RStudio or an R session, and `renv` will automatically provide access
# to all the necessary packages without any manual setup.


rule renv_snapshot:
    input:
        "resources/enrichment/enrichment_analyses_complete.done",
    output:
        touch(".renv_snapshot.done"),
    log:
        "logs/renv/snapshot.log",
    conda:
        "../envs/r_env.yaml"
    script:
        "../scripts/renv_snapshot.R"


rule renv_restore:
    input:
        ".renv_snapshot.done",
    output:
        touch(".renv_restore.done"),
    log:
        "logs/renv/restore.log",
    conda:
        "../envs/r_env.yaml"
    script:
        "../scripts/renv_restore.R"
