rule tximeta:
    input:
        indexDir="",
        source="",
        organism="",
        release="",
        genome="",
        fasta="",
        gtf="",
    output:
        se="se.RDS",
    params:
        extra=config["params"]["tximeta"]["extra"],
    conda:
        "../envs/tximeta.yaml"
    log:
        "logs/tximeta/tximeta.log",
    script:
        "../scripts/tximeta.R"
