# .test/local_reads/ensembl/config_complex/config.yaml

# Path to your SAMPLE SHEET which keeps track of your biological replicates
samples: ".test/local_reads/ensembl/config_complex/samples.tsv"

# Path to your sequencing UNIT SHEET which keeps track of your technical
# replicates (e.g. sequencer lanes or resequencing of the same biological
# sample)
units: ".test/local_reads/ensembl/config_complex/units.tsv"
