name: Build & Release Containers

on:
  push:
    tags:
      - "v*" # Trigger this workflow on version tags (like v1.0.0)

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build FastQC SIF using Singularity container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            quay.io/singularity/singularity:v3.8.4 \
            build /workspace/fastqc.sif /workspace/envs/fastqc.def

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "Pre-built containers for this release"
          draft: false
          prerelease: false

      - name: Upload SIF to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fastqc.sif
          asset_name: fastqc.sif
          asset_content_type: application/octet-stream
